version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      TOKEN: "$TOKEN"
      PREFIX: "$PREFIX"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
